# -*- coding: utf-8 -*-
"""Task-Alaa Adel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JC68f6tsKDNgigB0PUT8PWjp2ycZlzBD
"""

def group_sort(input_path):
  import pandas as pd
  from google.colab import files
  uploaded = files.upload()
  import io
  full_data = pd.read_csv(io.BytesIO(uploaded[input_path]))
  Dict = {}
  for i in range (full_data.job.size):
    if(full_data.job.iloc[i] in Dict):
      Dict[full_data.job.iloc[i]]=Dict.get(full_data.job.iloc[i])+1
    else:
      Dict[full_data.job.iloc[i]] = 1
    sorted_values = sorted(Dict.values()) 
  sorted_dict = {}
  for i in sorted_values:
    for k in Dict.keys():
      if Dict[k] == i:
        sorted_dict[k] = Dict[k]
        break
  print(sorted_dict)
  sorted_keys = sorted(Dict.keys()) 
  print(sorted_keys)

group_sort('jobs.csv')

